In [129]:
import pandas as pd
import numpy as np

In [130]:
data1=pd.read_csv('/data/phenotype.txt',engine="python",sep="\t")

In [131]:
#가족력, 과거력 파악
data2=data1.loc[:,['FCAN80','LUNG']]
data2.dropna(inplace=True)
print(len(data2))
data3=data2[data2['LUNG']==1]
print(len(data3))
print(len(data3)/len(data2))
data3.head()

396
21
0.05303030303030303

      FCAN80  LUNG
1508     1.0     1
2447     1.0     1
4574     1.0     1
4714     1.0     1
4831     1.0     1

In [132]:
data1['PCAN80']=data1['PCAN80'].fillna(0)
data1['FCAN80']=data1['FCAN80'].fillna(0)

In [133]:
#BMI 변수 만들기
data1_HT=data1['HT_B']
data1_WT=data1['WT_B']
data1_BMI=data1_WT/(data1_HT*data1_HT)*10000
data1_BMI

0        20.015031
1        23.046875
2        22.975779
3        25.273469
4        19.588207
           ...
16950    33.930904
16951    21.218317
16952    26.906122
16953    20.212808
16954    23.011177
Length: 16955, dtype: float64

In [134]:
data2=pd.concat([data1,data1_BMI],axis=1)
data2=data2.rename(columns={0:'bmi'})
data2

,FID,IID,AGE_B,SMOK_B,SMOKA_MOD_B,ALCO_B,ALCO_AMOUNT_B,EXER_B,MDM_B,MHTN_B,...,SPROST,STHROI,SBREAC,SLUNG,SSTOMA,SLIVER,SEX1,CRC,SCRC,bmi
0,KCPS000001,KCPS000001,39,1.0,0.0,1.0,NaN,1.0,NaN,NaN,...,11.5,2.000000,11.5,11.5,11.500000,11.5,2,0,11.500000,20.015031
1,KCPS000002,KCPS000002,44,1.0,NaN,1.0,0.000000,1.0,NaN,NaN,...,11.5,11.500000,11.5,11.5,11.500000,11.5,2,0,11.500000,23.046875
2,KCPS000003,KCPS000003,46,2.0,10.0,2.0,4.580357,1.0,NaN,NaN,...,11.5,11.500000,11.5,11.5,11.500000,11.5,1,0,11.500000,22.975779
3,KCPS000004,KCPS000004,43,1.0,0.0,2.0,5.571429,2.0,NaN,NaN,...,11.5,11.500000,11.5,11.5,11.500000,11.5,1,0,11.500000,25.273469
4,KCPS000005,KCPS000005,45,NaN,NaN,1.0,NaN,2.0,NaN,NaN,...,11.5,2.333333,11.5,11.5,11.500000,11.5,2,1,-12.083333,19.588207
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16950,KCPS016951,KCPS016951,40,3.0,25.0,2.0,3.714286,2.0,NaN,1.0,...,11.7,11.700000,11.7,11.7,11.700000,11.7,1,0,11.700000,33.930904
16951,KCPS016952,KCPS016952,48,1.0,NaN,1.0,0.000000,1.0,NaN,NaN,...,11.7,4.033333,11.7,11.7,11.700000,11.7,2,0,11.700000,21.218317
16952,KCPS016953,KCPS016953,50,2.0,NaN,2.0,NaN,1.0,NaN,NaN,...,2.7,2.700000,2.7,2.7,2.700000,2.7,1,0,2.700000,26.906122
16953,KCPS016954,KCPS016954,44,1.0,NaN,1.0,0.000000,1.0,NaN,NaN,...,11.7,11.700000,11.7,11.7,11.700000,11.7,2,0,11.700000,20.212808
16954,KCPS016955,KCPS016955,49,1.0,NaN,1.0,NaN,1.0,NaN,NaN,...,2.7,2.700000,2.7,2.7,0.033333,2.7,2,0,2.700000,23.011177

In [136]:
#data4의 경우 FEV1,FVC 제외
data3=data2.loc[:,['FID','FVC','AGE_B', 'SMOK_B', 'ALCO_B','EXER_B','SBP_B', 'DBP_B', 'CHO_B','LDL_B', 'TG_B', 'HDL_B', 'FBS_B', 'GOT_B', 'GPT_B', 'GGT_B', 'URIC_B','BIL', 'WBC', 'CREAT','SEX1', 'CRC','bmi','PCAN80','FCAN80','LUNG']]
data3.dropna(inplace=True)
data3

,FID,FVC,AGE_B,SMOK_B,ALCO_B,EXER_B,SBP_B,DBP_B,CHO_B,LDL_B,...,URIC_B,BIL,WBC,CREAT,SEX1,CRC,bmi,PCAN80,FCAN80,LUNG
0,KCPS000001,67.0,39,1.0,1.0,1.0,93.0,59.0,174.0,102.0,...,4.9,0.5,4.16,0.9,2,0,20.015031,0.0,0.0,0
1,KCPS000002,105.0,44,1.0,1.0,1.0,111.0,67.0,160.0,93.0,...,3.1,0.6,6.00,0.7,2,0,23.046875,0.0,0.0,0
2,KCPS000003,98.0,46,2.0,2.0,1.0,108.0,64.0,164.0,107.0,...,5.1,0.9,4.95,1.0,1,0,22.975779,0.0,0.0,0
3,KCPS000004,91.0,43,1.0,2.0,2.0,116.0,75.0,198.0,129.0,...,6.8,1.4,4.60,1.0,1,0,25.273469,0.0,0.0,0
6,KCPS000007,76.0,42,3.0,2.0,1.0,125.0,80.0,199.0,115.0,...,5.8,1.1,6.17,1.0,1,0,24.793388,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16950,KCPS016951,76.0,40,3.0,2.0,2.0,135.0,89.0,221.0,145.0,...,8.5,0.5,5.22,1.3,1,0,33.930904,0.0,0.0,0
16951,KCPS016952,88.0,48,1.0,1.0,1.0,103.0,71.0,184.0,109.0,...,4.3,0.5,5.99,0.8,2,0,21.218317,0.0,0.0,0
16952,KCPS016953,87.0,50,2.0,2.0,1.0,119.0,88.0,179.0,114.0,...,5.5,0.5,5.74,1.0,1,0,26.906122,0.0,0.0,0
16953,KCPS016954,117.0,44,1.0,1.0,1.0,119.0,72.0,143.0,82.0,...,4.6,0.7,3.79,0.9,2,0,20.212808,0.0,0.0,0
16954,KCPS016955,102.0,49,1.0,1.0,1.0,103.0,63.0,211.0,144.0,...,3.2,0.6,5.38,0.7,2,0,23.011177,0.0,0.0,0

In [137]:
dat1=pd.read_csv('/data/KCPS_r2_0.01.csv')

In [138]:
data1 = pd.concat([dat1,data3],axis=1)
data1.dropna(inplace=True)
data1

,FID,IID,rs4970382,rs7513297,rs144969472,rs1695860,rs3765908,rs34135959,1:1959861_GCC/G,rs12057498,...,URIC_B,BIL,WBC,CREAT,SEX1,CRC,bmi,PCAN80,FCAN80,LUNG
0,KCPS000001,KCPS000001,0,1,0,2,2,1,0,1,...,4.9,0.5,4.16,0.9,2.0,0.0,20.015031,0.0,0.0,0.0
1,KCPS000002,KCPS000002,0,1,0,0,2,0,1,2,...,3.1,0.6,6.00,0.7,2.0,0.0,23.046875,0.0,0.0,0.0
2,KCPS000003,KCPS000003,2,1,0,0,1,1,0,1,...,5.1,0.9,4.95,1.0,1.0,0.0,22.975779,0.0,0.0,0.0
3,KCPS000004,KCPS000004,0,1,0,1,2,0,0,0,...,6.8,1.4,4.60,1.0,1.0,0.0,25.273469,0.0,0.0,0.0
6,KCPS000007,KCPS000007,0,1,0,0,1,1,1,2,...,5.8,1.1,6.17,1.0,1.0,0.0,24.793388,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16950,KCPS016951,KCPS016951,0,0,0,0,0,0,0,1,...,8.5,0.5,5.22,1.3,1.0,0.0,33.930904,0.0,0.0,0.0
16951,KCPS016952,KCPS016952,0,0,0,0,1,2,1,0,...,4.3,0.5,5.99,0.8,2.0,0.0,21.218317,0.0,0.0,0.0
16952,KCPS016953,KCPS016953,1,2,1,1,1,0,1,0,...,5.5,0.5,5.74,1.0,1.0,0.0,26.906122,0.0,0.0,0.0
16953,KCPS016954,KCPS016954,0,0,0,0,2,1,1,1,...,4.6,0.7,3.79,0.9,2.0,0.0,20.212808,0.0,0.0,0.0
16954,KCPS016955,KCPS016955,2,0,0,1,1,1,2,2,...,3.2,0.6,5.38,0.7,2.0,0.0,23.011177,0.0,0.0,0.0

In [139]:
data1.drop('FID',axis=1,inplace=True)
data1.drop('IID',axis=1,inplace=True)

In [140]:
data1[data1['LUNG']==1]

,rs4970382,rs7513297,rs144969472,rs1695860,rs3765908,rs34135959,1:1959861_GCC/G,rs12057498,rs4648834,rs2840535,...,URIC_B,BIL,WBC,CREAT,SEX1,CRC,bmi,PCAN80,FCAN80,LUNG
34,0,0,0,1,0,1,0,0,1,0,...,5.7,0.7,9.70,1.0,1.0,0.0,25.874583,0.0,0.0,1.0
48,1,1,0,1,2,1,0,0,2,2,...,4.0,0.4,3.87,0.6,2.0,0.0,24.726562,0.0,0.0,1.0
51,2,0,0,0,0,1,0,2,1,1,...,4.6,0.6,6.48,0.9,2.0,0.0,24.049682,0.0,0.0,1.0
65,0,1,0,0,0,2,2,0,2,1,...,4.5,0.6,6.27,1.2,1.0,0.0,18.331352,0.0,0.0,1.0
113,0,0,0,0,0,1,2,0,2,0,...,5.1,0.8,4.15,0.7,2.0,0.0,26.523920,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16854,0,0,0,0,2,1,2,0,2,0,...,4.9,0.5,7.78,1.0,1.0,0.0,21.664973,0.0,0.0,1.0
16864,1,0,0,0,0,1,2,1,1,1,...,5.2,0.9,5.47,0.9,1.0,0.0,23.143447,0.0,0.0,1.0
16923,0,0,0,2,1,1,0,2,0,0,...,4.2,1.0,7.90,1.2,1.0,0.0,23.875433,0.0,0.0,1.0
16925,1,0,0,0,0,2,0,0,2,0,...,3.4,0.7,8.30,0.9,1.0,0.0,25.399656,0.0,0.0,1.0
16936,0,0,0,2,1,1,2,0,2,1,...,6.8,0.5,7.79,1.1,1.0,0.0,23.715154,0.0,0.0,1.0

In [141]:
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score,average_precision_score, recall_score, roc_auc_score # 평가
from sklearn.metrics import f1_score, confusion_matrix, precision_recall_curve, roc_curve
from sklearn.preprocessing import StandardScaler, Binarizer
from sklearn.model_selection import GridSearchCV, train_test_split

from sklearn.tree import DecisionTreeClassifier 
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import AdaBoostClassifier
from xgboost import XGBClassifier
import xgboost as xgb
from xgboost import plot_importance

from sklearn.model_selection import StratifiedKFold,cross_val_score, cross_validate

In [142]:
import re
data1 = data1.rename(columns = lambda x:re.sub('[^A-Za-z0-9_]+', '', x))

In [143]:
X_df = data1.iloc[:,:-1]
y_df = data1.iloc[:,-1]

In [144]:
# random_state = 156 : 다음에도 같은 데이터를 train, test로 분리 하는 옵션
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_df,y_df,test_size=0.2,random_state=156,stratify=y_df)

In [145]:
from sklearn.linear_model import Lasso
lasso = Lasso(alpha=0.0015, max_iter=1000).fit(X_train, y_train)

print("훈련 세트의 정확도 : {:.2f}".format(lasso.score(X_train, y_train)))
print("테스트 세트의 정확도 : {:.2f}".format(lasso.score(X_test, y_test)))
print("사용한 특성의 수 : {}".format(np.sum(lasso.coef_ != 0)))
print("사용한 max_iter : {}".format(lasso.n_iter_))

훈련 세트의 정확도 : 0.46
테스트 세트의 정확도 : -0.08
사용한 특성의 수 : 1989
사용한 max_iter : 109

In [146]:
from sklearn.linear_model import Lasso
lasso = Lasso(alpha=0.003, max_iter=1000).fit(X_train, y_train)

print("훈련 세트의 정확도 : {:.2f}".format(lasso.score(X_train, y_train)))
print("테스트 세트의 정확도 : {:.2f}".format(lasso.score(X_test, y_test)))
print("사용한 특성의 수 : {}".format(np.sum(lasso.coef_ != 0)))
print("사용한 max_iter : {}".format(lasso.n_iter_))

훈련 세트의 정확도 : 0.11
테스트 세트의 정확도 : 0.01
사용한 특성의 수 : 342
사용한 max_iter : 67

In [149]:
X_train.shape

(7010, 15212)

In [150]:
X_train.iloc[:,lasso.coef_!=0].columns

Index(['rs12728296', 'rs1750823', 'rs140296460', 'rs12125733', 'rs2816058',
       'rs485874', 'rs11247696', 'rs1679911', 'rs2298130', 'rs3754262',
       ...
       'SMOK_B', 'SBP_B', 'DBP_B', 'CHO_B', 'LDL_B', 'TG_B', 'GPT_B', 'GGT_B',
       'WBC', 'bmi'],
      dtype='object', length=342)

In [151]:
X_train_columns=X_train.iloc[:,lasso.coef_!=0].columns
X_test_columns=X_train.iloc[:,lasso.coef_!=0].columns

In [154]:
X_lasso=X_train[X_train_columns]
X_lasso=X_lasso.iloc[:,:330]
X_lasso

,rs12728296,rs1750823,rs140296460,rs12125733,rs2816058,rs485874,rs11247696,rs1679911,rs2298130,rs3754262,...,2123756676_CCAAAAAAAAAAAAAAAAAAA,rs2834442,rs631462,rs5993709,rs365892,rs4991265,rs728175,rs4822909,rs114010720,rs9616420
436,0,1,1,2,1,2,1,1,0,2,...,0,0,0,1,1,1,2,1,1,1
11313,0,2,0,0,1,1,0,1,1,0,...,0,2,0,0,0,0,0,0,0,1
1668,0,1,0,1,1,1,0,1,0,1,...,1,2,1,2,0,0,0,2,2,2
10323,2,1,0,2,2,0,1,1,0,1,...,0,0,1,0,1,2,0,0,0,1
9097,0,2,0,0,1,0,2,0,0,1,...,0,0,1,1,1,2,1,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16774,2,0,2,1,0,0,2,1,1,1,...,2,1,0,2,0,1,1,1,1,1
10441,2,1,0,0,1,1,1,1,1,2,...,2,2,1,1,0,1,1,2,1,1
1482,1,0,1,0,1,2,1,0,1,1,...,0,1,1,2,1,1,2,2,0,1
8214,0,2,0,0,0,1,2,0,1,1,...,0,1,1,1,0,1,1,0,1,0
5629,2,0,0,2,0,2,0,0,1,2,...,0,1,1,2,0,1,1,2,2,1

In [158]:
X_train_new = pd.concat([X_train.iloc[:,15188:15212],X_lasso],axis=1)
X_train_new

,FVC,AGE_B,SMOK_B,ALCO_B,EXER_B,SBP_B,DBP_B,CHO_B,LDL_B,TG_B,...,2123756676_CCAAAAAAAAAAAAAAAAAAA,rs2834442,rs631462,rs5993709,rs365892,rs4991265,rs728175,rs4822909,rs114010720,rs9616420
436,95.00,62.0,1.0,2.0,1.0,122.0,78.0,203.0,119.0,275.0,...,0,0,0,1,1,1,2,1,1,1
11313,4.19,37.0,2.0,2.0,1.0,100.0,60.0,194.0,116.0,130.0,...,0,2,0,0,0,0,0,0,0,1
1668,71.00,66.0,3.0,1.0,1.0,129.0,85.0,145.0,82.2,84.0,...,1,2,1,2,0,0,0,2,2,2
10323,2.26,36.0,1.0,1.0,1.0,111.0,69.0,198.0,100.0,240.0,...,0,0,1,0,1,2,0,0,0,1
9097,3.98,50.0,3.0,2.0,1.0,110.0,70.0,251.0,190.0,130.0,...,0,0,1,1,1,2,1,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16774,99.00,41.0,2.0,2.0,1.0,130.0,85.0,196.0,121.0,59.0,...,2,1,0,2,0,1,1,1,1,1
10441,4.89,31.0,1.0,2.0,1.0,114.0,64.0,223.0,160.0,90.0,...,2,2,1,1,0,1,1,2,1,1
1482,80.00,55.0,3.0,2.0,1.0,109.0,74.0,154.0,89.0,89.0,...,0,1,1,2,1,1,2,2,0,1
8214,3.01,65.0,3.0,2.0,1.0,130.0,80.0,136.0,64.6,82.0,...,0,1,1,1,0,1,1,0,1,0
5629,3.07,39.0,1.0,1.0,1.0,121.0,80.0,209.0,138.0,75.0,...,0,1,1,2,0,1,1,2,2,1

In [159]:
X_test_lasso = X_test[X_train_columns]
X_test_lasso = X_test_lasso.iloc[:,:330]
X_test_lasso

,rs12728296,rs1750823,rs140296460,rs12125733,rs2816058,rs485874,rs11247696,rs1679911,rs2298130,rs3754262,...,2123756676_CCAAAAAAAAAAAAAAAAAAA,rs2834442,rs631462,rs5993709,rs365892,rs4991265,rs728175,rs4822909,rs114010720,rs9616420
7700,0,1,2,1,1,2,2,0,1,0,...,2,1,1,2,1,1,0,0,1,1
8656,2,2,0,0,2,2,2,1,1,1,...,2,1,1,0,0,0,1,2,0,0
14458,2,0,0,0,0,1,1,1,0,1,...,1,2,0,1,1,1,2,0,0,2
641,0,2,2,1,1,1,1,0,1,1,...,1,0,1,2,1,0,0,0,0,2
9078,0,1,1,1,1,0,1,1,0,0,...,0,0,0,1,2,1,1,2,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1859,0,2,0,0,2,0,0,0,1,1,...,2,2,2,0,0,1,1,1,2,0
6759,0,2,1,0,1,1,1,2,1,0,...,1,1,2,1,1,1,1,1,1,1
9208,0,0,0,1,1,2,0,1,0,0,...,0,1,1,0,2,0,0,0,2,2
12336,1,1,0,0,0,1,1,1,1,0,...,1,0,2,0,0,1,0,0,1,1
16676,0,1,0,0,0,0,0,0,2,0,...,0,2,2,1,1,1,1,1,1,0

In [160]:
X_test_new = pd.concat([X_test.iloc[:,15188:15212],X_test_lasso],axis=1)
X_test_new

,FVC,AGE_B,SMOK_B,ALCO_B,EXER_B,SBP_B,DBP_B,CHO_B,LDL_B,TG_B,...,2123756676_CCAAAAAAAAAAAAAAAAAAA,rs2834442,rs631462,rs5993709,rs365892,rs4991265,rs728175,rs4822909,rs114010720,rs9616420
7700,4.44,38.0,2.0,2.0,1.0,120.0,70.0,217.0,131.2,169.0,...,2,1,1,2,1,1,0,0,1,1
8656,3.28,33.0,1.0,1.0,2.0,110.0,80.0,202.0,123.0,100.0,...,2,1,1,0,0,0,1,2,0,0
14458,3.72,43.0,1.0,2.0,1.0,110.0,70.0,206.0,136.8,66.0,...,1,2,0,1,1,1,2,0,0,2
641,127.00,54.0,1.0,1.0,2.0,125.0,85.0,206.0,147.0,75.0,...,1,0,1,2,1,0,0,0,0,2
9078,4.19,48.0,3.0,1.0,1.0,100.0,70.0,190.0,112.8,156.0,...,0,0,0,1,2,1,1,2,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1859,88.00,48.0,1.0,1.0,1.0,147.0,82.0,191.0,120.6,142.0,...,2,2,2,0,0,1,1,1,2,0
6759,3.10,31.0,1.0,2.0,2.0,110.0,70.0,164.0,89.2,84.0,...,1,1,2,1,1,1,1,1,1,1
9208,2.15,62.0,1.0,1.0,2.0,120.0,70.0,199.0,107.0,210.0,...,0,1,1,0,2,0,0,0,2,2
12336,2.57,32.0,1.0,2.0,1.0,100.0,60.0,158.0,84.2,79.0,...,1,0,2,0,0,1,0,0,1,1
16676,72.00,46.0,1.0,1.0,2.0,92.0,69.0,185.0,115.0,160.0,...,0,2,2,1,1,1,1,1,1,0

In [161]:
X_test =X_test_new
X_train = X_train_new

In [165]:
import optuna
from optuna import Trial
from optuna.samplers import TPESampler

In [166]:
def objective(trial:Trial) -> float:
    max_depth = trial.suggest_int('max_depth', 1, 10)
    max_leaf_nodes = trial.suggest_int('max_leaf_nodes', 2, 1000)
    n_estimators =  trial.suggest_int('n_estimators', 100, 500)
   
    rf = RandomForestClassifier(max_depth = max_depth, max_leaf_nodes = max_leaf_nodes,n_estimators = n_estimators,n_jobs=2,random_state=25)
    
    rf.fit(X_train, y_train)
    rf_pred = rf.predict_proba(X_test)[:,1]
    rf_score = roc_auc_score(y_test,rf_pred)
    return rf_score

In [167]:
sampler = TPESampler(seed=42)
study = optuna.create_study(
    study_name="rf_parameter_opt",
    direction="maximize",
    sampler=sampler,
)
study.optimize(objective, n_trials=10)
print("Best Score:", study.best_value)
print("Best trial:", study.best_trial.params)

[I 2022-02-16 15:57:10,289] A new study created in memory with name: rf_parameter_opt
[I 2022-02-16 15:57:12,430] Trial 0 finished with value: 0.6790071572298209 and parameters: {'max_depth': 4, 'max_leaf_nodes': 951, 'n_estimators': 393}. Best is trial 0 with value: 0.6790071572298209.
[I 2022-02-16 15:57:13,391] Trial 1 finished with value: 0.7030259035684266 and parameters: {'max_depth': 6, 'max_leaf_nodes': 157, 'n_estimators': 162}. Best is trial 1 with value: 0.7030259035684266.
[I 2022-02-16 15:57:14,544] Trial 2 finished with value: 0.6745116018440692 and parameters: {'max_depth': 1, 'max_leaf_nodes': 867, 'n_estimators': 341}. Best is trial 1 with value: 0.7030259035684266.
[I 2022-02-16 15:57:16,659] Trial 3 finished with value: 0.6892463258704566 and parameters: {'max_depth': 8, 'max_leaf_nodes': 22, 'n_estimators': 488}. Best is trial 1 with value: 0.7030259035684266.
[I 2022-02-16 15:57:18,034] Trial 4 finished with value: 0.6209469957464151 and parameters: {'max_depth': 9, 'max_leaf_nodes': 214, 'n_estimators': 172}. Best is trial 1 with value: 0.7030259035684266.
[I 2022-02-16 15:57:19,278] Trial 5 finished with value: 0.6891317083110465 and parameters: {'max_depth': 2, 'max_leaf_nodes': 305, 'n_estimators': 310}. Best is trial 1 with value: 0.7030259035684266.
[I 2022-02-16 15:57:21,332] Trial 6 finished with value: 0.6793382746236725 and parameters: {'max_depth': 5, 'max_leaf_nodes': 292, 'n_estimators': 345}. Best is trial 1 with value: 0.7030259035684266.
[I 2022-02-16 15:57:22,240] Trial 7 finished with value: 0.7002878174269632 and parameters: {'max_depth': 2, 'max_leaf_nodes': 293, 'n_estimators': 246}. Best is trial 1 with value: 0.7030259035684266.
[I 2022-02-16 15:57:23,287] Trial 8 finished with value: 0.6655841674944601 and parameters: {'max_depth': 5, 'max_leaf_nodes': 786, 'n_estimators': 180}. Best is trial 1 with value: 0.7030259035684266.
[I 2022-02-16 15:57:24,220] Trial 9 finished with value: 0.680153332823922 and parameters: {'max_depth': 6, 'max_leaf_nodes': 593, 'n_estimators': 118}. Best is trial 1 with value: 0.7030259035684266.

Best Score: 0.7030259035684266
Best trial: {'max_depth': 6, 'max_leaf_nodes': 157, 'n_estimators': 162}

In [168]:
def objective(trial:Trial) -> float:
    max_depth = trial.suggest_int('max_depth', 1, 100)
    max_leaf_nodes = trial.suggest_int('max_leaf_nodes', 2, 1000)
   
    DT = DecisionTreeClassifier(max_depth = max_depth, max_leaf_nodes = max_leaf_nodes,random_state=25)
    
    DT.fit(X_train, y_train)
    DT_pred = DT.predict_proba(X_test)[:,1]
    DT_score = roc_auc_score(y_test,DT_pred)
    return DT_score

In [169]:
sampler = TPESampler(seed=42)
study = optuna.create_study(
    study_name="DT_parameter_opt",
    direction="maximize",
    sampler=sampler,
)
study.optimize(objective, n_trials=10)
print("Best Score:", study.best_value)
print("Best trial:", study.best_trial.params)

[I 2022-02-16 15:57:24,239] A new study created in memory with name: rf_parameter_opt
[I 2022-02-16 15:57:24,870] Trial 0 finished with value: 0.532086548992639 and parameters: {'max_depth': 38, 'max_leaf_nodes': 951}. Best is trial 0 with value: 0.532086548992639.
[I 2022-02-16 15:57:25,250] Trial 1 finished with value: 0.532086548992639 and parameters: {'max_depth': 74, 'max_leaf_nodes': 600}. Best is trial 0 with value: 0.532086548992639.
[I 2022-02-16 15:57:25,542] Trial 2 finished with value: 0.5232800998446296 and parameters: {'max_depth': 16, 'max_leaf_nodes': 157}. Best is trial 0 with value: 0.532086548992639.
[I 2022-02-16 15:57:25,719] Trial 3 finished with value: 0.6022898041313263 and parameters: {'max_depth': 6, 'max_leaf_nodes': 867}. Best is trial 3 with value: 0.6022898041313263.
[I 2022-02-16 15:57:26,019] Trial 4 finished with value: 0.532086548992639 and parameters: {'max_depth': 61, 'max_leaf_nodes': 709}. Best is trial 3 with value: 0.6022898041313263.
[I 2022-02-16 15:57:26,111] Trial 5 finished with value: 0.7139591452077125 and parameters: {'max_depth': 3, 'max_leaf_nodes': 970}. Best is trial 5 with value: 0.7139591452077125.
[I 2022-02-16 15:57:26,413] Trial 6 finished with value: 0.532086548992639 and parameters: {'max_depth': 84, 'max_leaf_nodes': 214}. Best is trial 5 with value: 0.7139591452077125.
[I 2022-02-16 15:57:26,721] Trial 7 finished with value: 0.47456763709533634 and parameters: {'max_depth': 19, 'max_leaf_nodes': 185}. Best is trial 5 with value: 0.7139591452077125.
[I 2022-02-16 15:57:27,034] Trial 8 finished with value: 0.532086548992639 and parameters: {'max_depth': 31, 'max_leaf_nodes': 526}. Best is trial 5 with value: 0.7139591452077125.
[I 2022-02-16 15:57:27,343] Trial 9 finished with value: 0.532086548992639 and parameters: {'max_depth': 44, 'max_leaf_nodes': 292}. Best is trial 5 with value: 0.7139591452077125.

Best Score: 0.7139591452077125
Best trial: {'max_depth': 3, 'max_leaf_nodes': 970}

In [170]:
def objective(trial:Trial) -> float:
    n_neighbors = trial.suggest_int('n_neighbors', 1, 1000)
    leaf_size = trial.suggest_int('leaf_size', 1, 1000)
   
    KN = KNeighborsClassifier(n_neighbors=n_neighbors, algorithm='auto', leaf_size=leaf_size, metric='minkowski')
    
    KN.fit(X_train, y_train)
    KN_pred = KN.predict_proba(X_test)[:,1]
    KN_score = roc_auc_score(y_test,KN_pred)
    return KN_score

In [171]:
sampler = TPESampler(seed=42)
study = optuna.create_study(
    study_name="KN_parameter_opt",
    direction="maximize",
    sampler=sampler,
)
study.optimize(objective, n_trials=10)
print("Best Score:", study.best_value)
print("Best trial:", study.best_trial.params)

[I 2022-02-16 15:57:27,359] A new study created in memory with name: rf_parameter_opt
[I 2022-02-16 15:57:27,837] Trial 0 finished with value: 0.6475191666029902 and parameters: {'n_neighbors': 375, 'leaf_size': 951}. Best is trial 0 with value: 0.6475191666029902.
[I 2022-02-16 15:57:28,312] Trial 1 finished with value: 0.6303711061868011 and parameters: {'n_neighbors': 732, 'leaf_size': 599}. Best is trial 0 with value: 0.6475191666029902.
[I 2022-02-16 15:57:28,647] Trial 2 finished with value: 0.6435202873080156 and parameters: {'n_neighbors': 157, 'leaf_size': 156}. Best is trial 0 with value: 0.6475191666029902.
[I 2022-02-16 15:57:28,959] Trial 3 finished with value: 0.6510595756603245 and parameters: {'n_neighbors': 59, 'leaf_size': 867}. Best is trial 3 with value: 0.6510595756603245.
[I 2022-02-16 15:57:29,562] Trial 4 finished with value: 0.6454496828914189 and parameters: {'n_neighbors': 602, 'leaf_size': 709}. Best is trial 3 with value: 0.6510595756603245.
[I 2022-02-16 15:57:29,958] Trial 5 finished with value: 0.59020401925575 and parameters: {'n_neighbors': 21, 'leaf_size': 970}. Best is trial 3 with value: 0.6510595756603245.
[I 2022-02-16 15:57:30,455] Trial 6 finished with value: 0.6158592496370443 and parameters: {'n_neighbors': 833, 'leaf_size': 213}. Best is trial 3 with value: 0.6510595756603245.
[I 2022-02-16 15:57:30,795] Trial 7 finished with value: 0.656739512493314 and parameters: {'n_neighbors': 182, 'leaf_size': 184}. Best is trial 7 with value: 0.656739512493314.
[I 2022-02-16 15:57:31,176] Trial 8 finished with value: 0.6492193270675735 and parameters: {'n_neighbors': 305, 'leaf_size': 525}. Best is trial 7 with value: 0.656739512493314.
[I 2022-02-16 15:57:31,571] Trial 9 finished with value: 0.6468250936043402 and parameters: {'n_neighbors': 432, 'leaf_size': 292}. Best is trial 7 with value: 0.656739512493314.

Best Score: 0.656739512493314
Best trial: {'n_neighbors': 182, 'leaf_size': 184}

In [172]:
def objective(trial:Trial) -> float:
    n_estimators = trial.suggest_int('n_estimators', 1, 1000)
   
    AD = AdaBoostClassifier(n_estimators=n_estimators)
    
    AD.fit(X_train, y_train)
    AD_pred = AD.predict_proba(X_test)[:,1]
    AD_score = roc_auc_score(y_test,AD_pred)
    return AD_score

In [173]:
sampler = TPESampler(seed=42)
study = optuna.create_study(
    study_name="AD_parameter_opt",
    direction="maximize",
    sampler=sampler,
)
study.optimize(objective, n_trials=10)
print("Best Score:", study.best_value)
print("Best trial:", study.best_trial.params)

[I 2022-02-16 15:57:31,586] A new study created in memory with name: rf_parameter_opt
[I 2022-02-16 15:57:47,064] Trial 0 finished with value: 0.6689844884236265 and parameters: {'n_estimators': 375}. Best is trial 0 with value: 0.6689844884236265.
[I 2022-02-16 15:58:22,781] Trial 1 finished with value: 0.6226917297063242 and parameters: {'n_estimators': 951}. Best is trial 0 with value: 0.6689844884236265.
[I 2022-02-16 15:58:52,545] Trial 2 finished with value: 0.6286518427956496 and parameters: {'n_estimators': 732}. Best is trial 0 with value: 0.6689844884236265.
[I 2022-02-16 15:59:17,359] Trial 3 finished with value: 0.6379613356766257 and parameters: {'n_estimators': 599}. Best is trial 0 with value: 0.6689844884236265.
[I 2022-02-16 15:59:23,056] Trial 4 finished with value: 0.5955401034105092 and parameters: {'n_estimators': 157}. Best is trial 0 with value: 0.6689844884236265.
[I 2022-02-16 15:59:28,151] Trial 5 finished with value: 0.5965971320139579 and parameters: {'n_estimators': 156}. Best is trial 0 with value: 0.6689844884236265.
[I 2022-02-16 15:59:30,193] Trial 6 finished with value: 0.6249586103257686 and parameters: {'n_estimators': 59}. Best is trial 0 with value: 0.6689844884236265.
[I 2022-02-16 16:00:07,519] Trial 7 finished with value: 0.6273655790733806 and parameters: {'n_estimators': 867}. Best is trial 0 with value: 0.6689844884236265.
[I 2022-02-16 16:00:31,162] Trial 8 finished with value: 0.6413361860370342 and parameters: {'n_estimators': 602}. Best is trial 0 with value: 0.6689844884236265.
[I 2022-02-16 16:00:55,037] Trial 9 finished with value: 0.6221313771936527 and parameters: {'n_estimators': 709}. Best is trial 0 with value: 0.6689844884236265.

Best Score: 0.6689844884236265
Best trial: {'n_estimators': 375}

In [175]:
def objective(trial:Trial) -> float:
    n_estimators = trial.suggest_int('n_estimators', 1, 1000)
    min_child_weight = trial.suggest_int('min_child_weight', 0, 1000)
   
    XGB = XGBClassifier(n_estimators=n_estimators, min_child_weight=min_child_weight)
    
    XGB.fit(X_train, y_train)
    XGB_pred = XGB.predict_proba(X_test)[:,1]
    XGB_score = roc_auc_score(y_test,XGB_pred)
    return XGB_score

In [176]:
sampler = TPESampler(seed=42)
study = optuna.create_study(
    study_name="XGB_parameter_opt",
    direction="maximize",
    sampler=sampler,
)
study.optimize(objective, n_trials=10)
print("Best Score:", study.best_value)
print("Best trial:", study.best_trial.params)

[I 2022-02-16 16:06:32,100] A new study created in memory with name: rf_parameter_opt
/usr/local/lib64/python3.6/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[16:06:32] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

[I 2022-02-16 16:06:58,123] Trial 0 finished with value: 0.5 and parameters: {'n_estimators': 375, 'min_child_weight': 951}. Best is trial 0 with value: 0.5.
/usr/local/lib64/python3.6/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[16:06:58] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

[I 2022-02-16 16:08:33,028] Trial 1 finished with value: 0.7131377193652734 and parameters: {'n_estimators': 732, 'min_child_weight': 599}. Best is trial 1 with value: 0.7131377193652734.
/usr/local/lib64/python3.6/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[16:08:33] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

[I 2022-02-16 16:08:54,478] Trial 2 finished with value: 0.7605193448969716 and parameters: {'n_estimators': 157, 'min_child_weight': 156}. Best is trial 2 with value: 0.7605193448969716.
/usr/local/lib64/python3.6/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[16:08:54] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

[I 2022-02-16 16:09:02,037] Trial 3 finished with value: 0.5 and parameters: {'n_estimators': 59, 'min_child_weight': 867}. Best is trial 2 with value: 0.7605193448969716.
/usr/local/lib64/python3.6/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[16:09:02] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

[I 2022-02-16 16:10:21,235] Trial 4 finished with value: 0.699294465245409 and parameters: {'n_estimators': 602, 'min_child_weight': 708}. Best is trial 2 with value: 0.7605193448969716.
/usr/local/lib64/python3.6/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[16:10:21] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

[I 2022-02-16 16:10:24,239] Trial 5 finished with value: 0.5 and parameters: {'n_estimators': 21, 'min_child_weight': 970}. Best is trial 2 with value: 0.7605193448969716.
/usr/local/lib64/python3.6/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[16:10:24] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

[I 2022-02-16 16:13:50,760] Trial 6 finished with value: 0.7230648735386261 and parameters: {'n_estimators': 833, 'min_child_weight': 212}. Best is trial 2 with value: 0.7605193448969716.
/usr/local/lib64/python3.6/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[16:13:51] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

[I 2022-02-16 16:14:42,165] Trial 7 finished with value: 0.7576730088382873 and parameters: {'n_estimators': 182, 'min_child_weight': 183}. Best is trial 2 with value: 0.7605193448969716.
/usr/local/lib64/python3.6/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[16:14:42] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

[I 2022-02-16 16:16:02,242] Trial 8 finished with value: 0.723911769949823 and parameters: {'n_estimators': 305, 'min_child_weight': 525}. Best is trial 2 with value: 0.7605193448969716.
/usr/local/lib64/python3.6/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[16:16:02] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

[I 2022-02-16 16:17:56,647] Trial 9 finished with value: 0.7394551845342707 and parameters: {'n_estimators': 432, 'min_child_weight': 291}. Best is trial 2 with value: 0.7605193448969716.

Best Score: 0.7605193448969716
Best trial: {'n_estimators': 157, 'min_child_weight': 156}

In [177]:
from lightgbm import LGBMClassifier
def objective(trial:Trial) -> float:
    n_estimators = trial.suggest_int('n_estimators', 1, 1000)
    max_depth = trial.suggest_int('max_depth', -1, 1000)
   
    LGBM = LGBMClassifier(n_estimators=n_estimators, max_depth=max_depth)
    
    LGBM.fit(X_train, y_train)
    LGBM_pred = LGBM.predict_proba(X_test)[:,1]
    LGBM_score = roc_auc_score(y_test,LGBM_pred)
    return LGBM_score

In [178]:
sampler = TPESampler(seed=42)
study = optuna.create_study(
    study_name="LGBM_parameter_opt",
    direction="maximize",
    sampler=sampler,
)
study.optimize(objective, n_trials=10)
print("Best Score:", study.best_value)
print("Best trial:", study.best_trial.params)

[I 2022-02-16 16:17:56,696] A new study created in memory with name: rf_parameter_opt
[I 2022-02-16 16:27:12,632] Trial 0 finished with value: 0.6800005094113751 and parameters: {'n_estimators': 375, 'max_depth': 951}. Best is trial 0 with value: 0.6800005094113751.
[I 2022-02-16 16:46:26,902] Trial 1 finished with value: 0.675288454191182 and parameters: {'n_estimators': 732, 'max_depth': 598}. Best is trial 0 with value: 0.6800005094113751.
[I 2022-02-16 16:56:06,205] Trial 2 finished with value: 0.6864190927383408 and parameters: {'n_estimators': 157, 'max_depth': 155}. Best is trial 2 with value: 0.6864190927383408.
[I 2022-02-16 16:59:27,838] Trial 3 finished with value: 0.6995364356486081 and parameters: {'n_estimators': 59, 'max_depth': 866}. Best is trial 3 with value: 0.6995364356486081.
[I 2022-02-16 17:16:25,646] Trial 4 finished with value: 0.6792236570642621 and parameters: {'n_estimators': 602, 'max_depth': 708}. Best is trial 3 with value: 0.6995364356486081.
[I 2022-02-16 17:17:12,552] Trial 5 finished with value: 0.6614706706400755 and parameters: {'n_estimators': 21, 'max_depth': 970}. Best is trial 3 with value: 0.6995364356486081.
[I 2022-02-16 17:23:14,710] Trial 6 finished with value: 0.6756959832913069 and parameters: {'n_estimators': 833, 'max_depth': 211}. Best is trial 3 with value: 0.6995364356486081.
[I 2022-02-16 17:23:17,802] Trial 7 finished with value: 0.6885968263671328 and parameters: {'n_estimators': 182, 'max_depth': 182}. Best is trial 3 with value: 0.6995364356486081.
[I 2022-02-16 17:23:22,240] Trial 8 finished with value: 0.681159420289855 and parameters: {'n_estimators': 305, 'max_depth': 524}. Best is trial 3 with value: 0.6995364356486081.
[I 2022-02-16 17:23:24,923] Trial 9 finished with value: 0.6781666284608135 and parameters: {'n_estimators': 432, 'max_depth': 290}. Best is trial 3 with value: 0.6995364356486081.

Best Score: 0.6995364356486081
Best trial: {'n_estimators': 59, 'max_depth': 866}